### ISSUE TITLE
Not working with 0.96.1

### ISSUE THREAD

**Issue by Ssupreme** [Nitepone/flipper-intervalometer#3]
Not working with release 0.96.1. It says it needs some changes with api. Thanks a lot!

**Comment by Nitepone** [comment]
Hey! It looks like the nightly built successfully yesterday on 0.96.1 and on the latest flipper dev branch. https://github.com/Nitepone/flipper-intervalometer/actions/runs/7148264158

Could you please provide a full copy of your local build log?

**Comment by Ssupreme** [comment]
Sorry, I'm new to it, don't know how to do it. I updated flipper via phone app, and later intervalometer stopped working. There is no update for intervalometer in the phone app.  I installed last build you suggested, and it works! Thanks!

**Comment by Nitepone** [comment]
Ah, yeah. The app was originally uploaded to the flipper store without my knowledge, and without a software license.

I made a PR to get it added back to the app catalogue with an appropriate license. But it hasn't been approved yet.

Sorry for the inconvenience! Glad to hear the nightly build worked for you!
